### PR TITLE
Optionally convert numbers in CSV files

### LINKED ISSUE #264: Process imported CSV files on the fly for light type conversion
Hi!

I hope this hasn't been brought up before.

A user of the `ob-dsq` Emacs integration noticed in https://github.com/fritzgrabo/ob-dsq/issues/1 that all cell values of an imported CSV file are unconditionally parsed into strings.

Here's an example:

```shell
$ cat scores.csv
Name,Score
Fritz,90
Rainer,95
Fountainer,100

$ dsq --schema --pretty scores.csv
Array of
  Object of
    Name of
      string
    Score of
      string
```

I see how CSV doesn't carry type information for individual values, so treating everything as strings is probably the safest option. Also, it's what Go's [CSV reader](https://pkg.go.dev/encoding/csv#Reader.Read) does by default.

At the same time, it leads to unexpected results in queries:

```shell
$ dsq --pretty scores.csv "select * from {} where Score > 90"
+--------+-------+
|  Name  | Score |
+--------+-------+
| Rainer |    95 |
+--------+-------+
(1 row)
```

As a user, you'd have to know a bit about data types, operators and file formats to see what's going on here. You'd also have to know a bit about SQLite to come up with a way to work around the issue by type-casting values in the query:

```shell
$ dsq --pretty scores.csv "select * from {} where cast(Score as int) > 90"
+------------+-------+
|    Name    | Score |
+------------+-------+
| Rainer     |    95 |
| Fountainer |   100 |
+------------+-------+
(2 rows)
```

To help with this, I propose to do some light post-processing of the individual values of read CSV rows as they're imported in `transformCSV` (reads CSV rows as array of strings) and passed into `recordToMap` (luckily accepts arrays of _any_ type).

It'd probably suffice to let `strconv.Atoi` and `strconv.ParseFloat` try to convert the read value, and to keep it a string if they can't?

One downside of this is decreased performance, though. I came up with a naive implementation of my proposal and the effect is pretty visible in `Test_transformCSV_BENCHMARK` for a [CSV file with 24.6M rows / 18 columns](https://data.cityofnewyork.us/Transportation/2020-Yellow-Taxi-Trip-Data/kxp8-n2sj).

```shell
# unpatched
$ BENCHMARK=true go test -run Test_transformCSV_BENCHMARK
transform csv took 4m16.018390038s
PASS

# patched
$ dsq --schema --pretty scores.csv
Array of
  Object of
    Name of
      string
    Score of
      number

$ BENCHMARK=true go test -run Test_transformCSV_BENCHMARK
transform csv took 6m34.630924444s
PASS
```

The new caching feature probably helps with this: if a user has a CSV file of considerable size, I assume they'll use caching, so at least they'd have to take the performance hit only once.

In any case, before I start working on a proper PR for this, I wanted to ask your opinion:

- Is the issue an actual issue or should users just RTFM and learn to cast where needed?
- Is type conversion in CSV files too much magic?
- Is the decrease in performance worth the positive effect?; and related:
- Should this be a panel setting / `dsq` command line flag of some sorts?

Thanks!

### PR DESCRIPTION
**Pull request by fritzgrabo**
Resolves #264 

Here's what I got so far. I gave this a try from `dsq` (PR coming soon) and it works well!

```shell
$ cat ~/scores.csv
Name,Score
Fritz,90
Rainer,95
Fountainer,100

$ ./dsq --schema --pretty ~/scores.csv
Array of
  Object of
    Name of
      string
    Score of
      string

$ ./dsq --schema --pretty --convert-numbers ~/scores.csv
Array of
  Object of
    Name of
      string
    Score of
      number
```

At this point, I'm not sure if I should add a `convertNumbers` flag to the literal and http panels too, or just assume `false` there. Theoretically, it'd make sense to convert numbers from downloaded CSV files, too?

Let me know what you think. Thanks!

### CODE REVIEW

File: runner/file.go [hunk 1]
```diff
@@ -119,7 +136,11 @@ func transformCSV(in *bufio.Reader, out *bufio.Writer, delimiter rune) error {
 				continue
 			}
 
-			recordToMap(row, &fields, record)
+			if convertNumbers {
+				recordToMap(row, &fields, convertNumbersInRecord(record))
+			} else {
+				recordToMap(row, &fields, record)
+			}
```
Comment (eatonphil) [inline runner/file.go:143]: I think we can do the convertNumbersInRecord function *inside* of recordToMap which also iterates over all fields.

**Comment by eatonphil** [comment]
Nice work!

> At this point, I'm not sure if I should add a convertNumbers flag to the literal and http panels too, or just assume false there. Theoretically, it'd make sense to convert numbers from downloaded CSV files, too?

Good point! The better place to put the flag would be on the ContentType struct https://github.com/multiprocessio/datastation/blob/main/runner/state.go#L67. Just add a new top-level flag to that struct. Then everyone can pass into the transformX functions the right setting.

**Comment by fritzgrabo** [comment]
> [...] to put the flag would be on the ContentType struct

Good call; updated!

**Comment by fritzgrabo** [comment]
> [...] can do the convertNumbersInRecord function inside of recordToMap

I gave this a try, and promptly ran into some typing issues that I resolved using `reflect`. That felt more heavy-weight than it should have. I assume there's a cleaner way to do this, but my go-fu isn't strong enough yet, haha.

That said, I'm not sure I prefer the changes that this last commit introduces to what we had before: The innocent sounding `recordToMap` helper function is now _also_ responsible for number conversion, which seems like it's really doing 2 things at once? I felt like the number conversion thing was more related to the _transformation_ task that `transformCSV` handles.

Let me know what you think. Thanks!

File: runner/file.go [hunk 2]
```diff
@@ -89,7 +91,32 @@ func recordToMap[T any](row map[string]any, fields *[]string, record []T) {
 	}
 }
 
-func transformCSV(in *bufio.Reader, out *bufio.Writer, delimiter rune) error {
+func maybeConvertNumber(value any, convertNumbers bool) any {
+	if !convertNumbers {
```
Comment (eatonphil) [inline runner/file.go:95]: Here's what you can do without reflection:

```
func maybe(...)... {
  if !convertNumbers {
    return value
  }

  s, ok := value.(string)
  if !ok {
    return value
  }

  return convert(s)
}
```

Comment (eatonphil) [reply runner/file.go:95]: Reflection is more expensive IIRC

**Comment by eatonphil** [comment]
> That said, I'm not sure I prefer the changes that this last commit introduces to what we had before: The innocent sounding recordToMap helper function is now also responsible for number conversion, which seems like it's really doing 2 things at once? I felt like the number conversion thing was more related to the transformation task that transformCSV handles.

I would agree with you in all normal programming situations but this code is *the* hot loop. Code that runs here runs N*M times as the dataset imported into DataStation grows. So looping over all fields twice could be meaningful especially as not just the number of rows N grows but number of columns M grows too. Maybe 2*N*M isn't so bad but just something I'm thinking about.

**Comment by eatonphil** [comment]
Looks good! Merging.

**Comment by fritzgrabo** [comment]
Woohoo! Thanks!
